scorecard:
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/marketplace.redhat.com_v1alpha1_marketplaceconfig_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_meterbase_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_meterdefinition_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_razeedeployment_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/marketplace.redhat.com_v1alpha1_marketplaceconfig_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_meterbase_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_meterdefinition_cr.yaml"
          - "deploy/crds/marketplace.redhat.com_v1alpha1_razeedeployment_cr.yaml"
        csv-path: "deploy/olm-catalog/redhat-marketplace-operator/manifests/redhat-marketplace-operator.clusterserviceversion.yaml"
