apiVersion: marketplace.redhat.com/v1alpha1
kind: MarketplaceConfig
metadata:
  name: marketplaceconfig
spec:
  # Add fields here 
  rhmAccountID: wrong
  clusterUUID: wrong-cluster-uuid
  deploySecretName: rhm-operator-secret
 
