apiVersion: marketplace.redhat.com/v1alpha1
kind: RazeeDeployment
metadata:
  name: rhm-marketplaceconfig-razeedeployment
spec:
  # Add fields here
  enabled: true
  clusterUUID: example-cluster-uuid
