name: Build

on:
  push:
    branches: [ master, develop, feature/*, hotfix/*, release/*, bugfix/* ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE_REGISTRY: quay.io/rh-marketplace

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check licenses - run 'make add-licenses' if this errors
      run: make check-licenses

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: make build

    - name: Test
      run: make test
