name: Operator SDK

operator-sdk-install:
    name: Install Operator SDK
    needs: [ build ]
    env:
      OPERATOR_IMAGE: "quay.io/rh-marketplace/redhat-marketplace-operator:${{ needs.build.outputs.tag }}"

    steps:
      - name: Install operator-sdk
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu.asc
          gpg --verify operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu.asc
          chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        with:
          RELEASE_VERSION=v0.17.1
