name: Create Release

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Release
      run: make release
