name: Deploy

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get Version
        id: version
        run: echo "::set-output name=version::$(go run scripts/version version)"

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: build/Dockerfile
          registry: quay.io
          repository: rh-marketplace/redhat-marketplace-operator
          tag_with_sha: true
          tag_with_ref: true
          add_git_labels: true
          labels: version=${{ }}
          push: false
